#!/bin/sh
#restarting postgres to make sure that RCCN connects to it, sleeping just to be sure that it's up :)
#/etc/init.d/postgresql restart
#/bin/sleep 10
#exec 2>&1
export PYTHONPATH=$PYTHONPATH:/opt/rhizomatica/rccn
#exec /usr/local/freeswitch/bin/freeswitch
exec /usr/bin/freeswitch >> /var/log/freeswitch.log 2>&1
